export class createCaseModel {
    id: number = 0;
    companyName: string = '';
    crNum: string = '';
    natAdd: string = '';
    dirID: string = '';
    appPhn: string = '';
    appEmail: string = '';
    appPosition: string = '';
    appName: string = '';
    appManPhn: string = '';
    appManEmail: string = '';
    appManPosition: string = '';
    appManName: string = '';
    appAltPhn: string = '';
    appAltEmail: string = '';
    appAltPosition: string = '';
    appAltName: string = '';
    defName: string = '';
    defId: string = '';
    defCrocReq: string = '';
    defPhn: string = '';
    defAdd: string = '';
    claimAllegation: string = '';
    claimLawsuit: string = '';
    claimDamages: string = '';
    claimAmt: string = '';
}
